- name: Update apt cache
  apt:
    update_cache: yes

- name: Install packages
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - htop
    - unzip
    - p7zip-full
    - tree
    - curl
    - iftop
    - iotop
    - unrar-free
    - bzip2
    - bc

- name: common | set vim as default editor
  command: update-alternatives --set editor /usr/bin/vim.basic
